### ISSUE TITLE
Configuration in Apex 5

### ISSUE THREAD

**Issue by Oracleriet** [Dani3lSun/apex-plugin-dropzone#1]
Hi Daniel,

It would be helpful if you added a demo app , so we could see how you configured your apex page . I have trouble getting your plugin to work, but I would really like to see it work as it really improves the user experience.

**Comment by Dani3lSun** [comment]
Hi Oracleriet,
the plugin is still very beta and I don´t recommend to use it in production apps. All my plugins are very well documented within the plugin itself, simply create the region and let you show the help pages for each attribute that can be set.
It is planed to rewrite the plugin to not use a application process instead a ajax call of the plugin should be used. Also the plugin has problems if any items are on the plugins page or on global page 0.
