### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by sehgalp** [Dani3lSun/apex-plugin-dropzone#12]
if ("COMPLETE" == a.callbackEvent)
                    try {
                        var c = "return " + a.callbackFnc.replace(/;+$/, "") + ";"
                          , d = (new Function(c))();

That comma before d is a typo preventing the callback....

**Comment by Dani3lSun** [comment]
Hi @sehgalp 
I can not reproduce your issue. Even the sample app uses this callback function with Event "On Complete".
You pasted the minified code (optimized with Google Closure Compiler). The original code looks like that:
```
if (vOptions.callbackEvent == 'COMPLETE') {
    try {
        var fncString = "return " + vOptions.callbackFnc.replace(/;+$/, '') + ";";
        var customFnc = new Function(fncString)();
        apexDropzone.doCallback(customFnc());
    } catch (err) {
        console.log(err);
    }
}
```
But this doesn´t matter, you only have to insert a valid Javascript **function** to this field, like:
```
function alertOnComplete() {
    alert("All files uploaded successfully!");
}
```
Does this work?
But you also have the possibility to use native APEX Dynamic Action Events instead, e.g Event "Dropzone upload completed [Dropzone]" from the event select list...
