### ISSUE TITLE
PL/SQL code incompatible with prior versions

### ISSUE THREAD

**Issue by jeffreykemp** [Dani3lSun/apex-plugin-dropzone#16]
### Expected behavior
Existing PL/SQL Code (Upload) on existing dropzone plugins should continue to work after upgrading DropZone to the latest version.

### Actual behavior
It appears some of the attribute mappings have changed - e.g. filename is mapped to x02 instead of x01 as it was previously.

### Steps to reproduce the issue
Take a dropzone that was built in (e.g.) Dropzone v1.8. The sample code maps filename from apex_application.g_x01.
Upgrade application to Dropzone v1.9.5. The filename is no longer mapped because the plugin now populate it in apex_application.g_x02.

### APEX version (4.2.6 / 5.0.3)
5.0.4

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
n/a

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
n/a

**Comment by jeffreykemp** [comment]
Upgrades to the plugin should avoid breaking existing implementations - note that upgrading a plugin cannot change the plugin attributes.

One way to insulate implementations from changes in the plugin is to wrap the PL/SQL in an extra PL/SQL block which sets some variables, e.g. p_filename and p_mimetype before calling the custom code.

Alternatively, considering that the reason I customise the PL/SQL code is to change the name of the Apex collection used (in order to make it work with multiple dropzones on a page). Perhaps the apex collection name could be added as a new attribute on the plugin.

**Comment by Dani3lSun** [comment]
Hey @jeffreykemp 
yeah I´m aware of the problem that plugin updates doesn´t touch the attributes of already used plugins.
Unfortunately this is the downside providing as much customization possibilities to the developer as possible...
But you idea sounds good, I´m changing the code base to have all variables (l_filename,l_blob,l_mime_type, ...) in the main plugin code & in the PL/SQL Code (Upload) Attribute only the create_collection statement.
So a developer can do his own insert statement, but without to much code to get the information from the AJAX call...
Unfortunately you also need to change this attribute as of the release of v1.9.6 :(
But from then on it should stay update save

**Comment by jeffreykemp** [comment]
thanks, that would be good.

**Comment by Dani3lSun** [comment]
Ok, I checked the existing implementation and it is not possible to declare variables outside of the PLSQL block from the attribute. Thus I am using a PLSQL Code Field, it is validated from APEX if you enter invalid code. So the variables are declared outside (in the main plugin code), these are not known to the code in the code input field, so this code stays invalid...
And of course I am running out of attributes, already using all 25 that are available for regions...
I am planning a 2.0 release in the next days/weeks and there would be some major changes like:
- No JS Callback Function --> Use Plugin events
- No "Refresh Region after upload (STATIC_ID)" --> Use Plugin events
- No PLSQL code anymore --> Instead a field for the Collection Name (And maybe the possibility to enter a table name with mime_type, file_name, blob columns, but only if the 25 attributes are not exceeded)
Do you have any feature requests or additional ideas for a 2.0 release? Please let me know...

**Comment by jeffreykemp** [comment]
I think a 2.0 release with the changes you list would be a good idea. Using plugin events and attributes are the best way of allowing developers to customise the behaviour of the plugin. Having the collection name as an attribute would be the only requirement I think.

You will also be able to remove the "Page Items to Submit" attribute.

If you need to thin out the number of attributes, I would suggest that the following attributes could maybe be made into component-level attributes:

* File too big message
* Max files exceeded message

Another attribute that could be removed is "Logging". This isn't needed as you can control logging by checking if Apex is in Debug mode or not.

**Comment by Dani3lSun** [comment]
Hey @jeffreykemp 

was faster than I thought. Today I finished Version 2.0.0. :) 
You can see the Details in the Readme...

Version 2 got a new Internal Name, so you will be able to install it beside Version 1 in your Apps. So you can migrate to the new version more easily...If the Collection Name was the only thing you changed in the previous version than the upgrade will be straight forward...Don´t forget to replace custom DAs that get triggered by Events from the old version...

Here are the new settings:
<img width="773" alt="application_settings" src="https://cloud.githubusercontent.com/assets/698942/21572484/9ae96dd2-ced9-11e6-94c9-e89a182abe21.png">
<img width="290" alt="component_settings" src="https://cloud.githubusercontent.com/assets/698942/21572485/9aedd7be-ced9-11e6-8081-30e95af5e95f.png">

**Comment by jeffreykemp** [comment]
Looks great, I'm looking forward to trying it out! Thanks

**Comment by jeffreykemp** [comment]
All works well - only had one problem when I upgraded just one dropzone but left another dropzone on the older version. After upgrading both, they work smoothly.

I noticed the Chunked upload doesn't work on my system, using Apache 2.4 - should I expect it to?

Thanks for all your hard work!

**Comment by Dani3lSun** [comment]
Thanks for the props!:)

It should work well with Apache24, in my setting it works well on the first machine with Tomcat 8 with ORDS 3 and on the second machine with Apache24 as Proxy and behind that Tomcat 8 with ORDS 3...
How does your setup exactly look? Can you please try to enable Debug Mode and check if there are some Log Output?

Thanks for your help!;)

**Comment by jeffreykemp** [comment]
My env is Apache 2.4 - Oracle EPG - Oracle 11gXE on SUSE Linux.
The debug log shows:

**POST https://jk64.com/apex/wwv_flow.show 400 (Bad Request)**
send @ jquery-2.1.3.js?v=5.0.4.00.12:8625
ajax @ jquery-2.1.3.js?v=5.0.4.00.12:8161
(anonymous) @ apexdropzone.js:245
next @ apexdropzone.js:83
asyncLoop @ apexdropzone.js:98
(anonymous) @ apexdropzone.js:240

**debug.js?v=5.0.4.00.12:247 uploadDzFilesChunked Error error**

**Comment by Dani3lSun** [comment]
Ah ok, completely forgot about EPG...
EPG is similar to the old OHS/WebTier and can only handle Parameters that don´t exceed 32kb. Thus the chunked Method uploads 1MB Chunks this Method won´t work in combination with EPG!
I will include a EPG Note in the Readme & Help Page!
