### ISSUE TITLE
Upload to Cloud 

### ISSUE THREAD

**Issue by Fatehcis** [Dani3lSun/apex-plugin-dropzone#18]
### Expected behavior
Actually, it is a feature request, you've done an amazing job. It would really be nice if you add options for direct upload to Amazon and Oracle Cloud Storage.

**Comment by jeffreykemp** [comment]
Is there a single one-size-fits-all standard method for uploading to the "cloud"? I wouldn't want the plugin to be complicated with all the different parameters needed to support all the different cloud storage providers and methods for uploading - these are better served with custom code outside the plugin.

**Comment by Dani3lSun** [comment]
Hi @Fatehcis 

you already asked this kind of question some months ago, the answer is still the same. The Plugin handles the file upload process to DB, from there you should use custom code to upload it further to external storages!
More detailed answer from the past:
https://github.com/Dani3lSun/apex-plugin-dropzone/issues/5
