### ISSUE TITLE
The apex-plugin-dropzone Apex Sample

### ISSUE THREAD

**Issue by samt007** [Dani3lSun/apex-plugin-dropzone#2]
I can not successful to deploy the apex-plugin-dropzone.
Could provide me the Apex app sample(57743)?
Thanks a lot.

**Comment by Dani3lSun** [comment]
Hi samt007,

the dropzone plugin is overall still not ready for production use (in beta). Therefore a official release is not ready yet...But I will produce a little demo app the next days and then will publish the export. I come back to you soon!

**Comment by samt007** [comment]
Hi Daniel,
Thanks for your great job with Oracle Apex.
And I holp the export in the next days.
Thanks.

**Comment by Dani3lSun** [comment]
Hi samt007,
sorry for the delay, was a bit stressful the last days before holidays...
I have created a demo app, you can find the export sql file in the source folder of this plugin:
https://github.com/Dani3lSun/apex-plugin-dropzone/blob/master/source/apex_demo_app.sql

**Comment by samt007** [comment]
Hi Daniel,
Thanks and Merry Christmas!

**Comment by rodriformiga** [comment]
Hi @Dani3lSun 
I don't localize the source of demo App.
Could provide me the Apex app sample again?

**Comment by a1b0r** [comment]
Hi @Dani3lSun 
Could provide me the Apex app sample again?

**Comment by Dani3lSun** [comment]
@a1b0r 
I added a demo app to the newest release under
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v1.9.4
or direct download:
https://github.com/Dani3lSun/apex-plugin-dropzone/files/466069/f610_dropzone_demo.zip
