### ISSUE TITLE
Before Start of Upload Dynamic Action does not fire

### ISSUE THREAD

**Issue by hairpin666** [Dani3lSun/apex-plugin-dropzone#20]
### Expected behavior
Dynamic Action "Before Start of File Upload" is suppose to fire before upload process, the idea is, to force the user to set an  item before the upload starts (e.g. to set a document category etc.)

### Actual behavior
DA does not fire

### Steps to reproduce the issue
Create Dropzone , add DA with event before start of file upload, Selection type: region, Affected elements: Dropzone region.

### APEX version (4.2.6 / 5.0.3)
5.03

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS 3

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Firefox / IE

**Comment by Dani3lSun** [comment]
Hi @hairpin666 

such an event does not exist for the Dropzone Plugin...
In the Readme are all available Events listed:
https://github.com/Dani3lSun/apex-plugin-dropzone#plugin-events
<img width="387" alt="bildschirmfoto 2017-02-16 um 15 19 00" src="https://cloud.githubusercontent.com/assets/698942/23024670/8782672e-f45b-11e6-9b7e-125ba44f3922.png">

**Comment by hairpin666** [comment]
Oh, must have been the wrong plugin then :). Having this DA would be great though.
