### ISSUE TITLE
Data Not saving and remove file not showing

### ISSUE THREAD

**Issue by munirhub** [Dani3lSun/apex-plugin-dropzone#21]
Hello,

I have followed your instruction as mentioned in help file. However, I'm facing the issues is that I cant save data in APEX_COLLECTION and also don't showing "Remove File" as showing  in your demo application. My DB version 11gR2, Oracle Apex 5.0.3 amd ORDS 3.0 with https SSL.

![errr](https://cloud.githubusercontent.com/assets/26344238/23823096/15332bf4-0685-11e7-8013-2aec5d5e2028.jpg)

**Comment by Dani3lSun** [comment]
Hi @munirhub 
under the current release you will find a demo app, which you can download and import to your workspace. There you can see which Plugin Settings & Dynamic Actions I used...
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v2.0.3

**Comment by munirhub** [comment]
Hi Daniel, I'm really so glad and thank you so much  to get such a quick response from you. I was missing Ajax call back and some dynamic actions. Now it is working! However, I face the same problem of your signature and screen capture Plug in. I'd be grateful if you could also send those Demo apps . Thanks Its really Excellent which may met my clients requirements!! With LOVE. Munir.

**Comment by Dani3lSun** [comment]
Hey @munirhub 
you will find a demo of the signature plugin on the same place --> github release tab of signature plugin:
https://github.com/Dani3lSun/apex-plugin-apexsignature/releases/tag/v1.1
