### ISSUE TITLE
Dynamic Action not triggering

### ISSUE THREAD

**Issue by nikhilbutani** [Dani3lSun/apex-plugin-dropzone#26]
### Expected behavior
Alert should be fired once File is uploaded.

### Actual behavior
dynamic action is not fired.

### Steps to reproduce the issue
- Added Region
    Dropzone 2 [Plug-in]
![drag drop - region attributes](https://user-images.githubusercontent.com/6183829/28619814-dd42b106-7227-11e7-8b18-e68f6e7cde32.png)

- Create New DA
    Name : DA1
    Event : Dropzone Chunked File Upload Success (AJAX)
    Selection Type : Region
    Region : 'My Region - Drag & Drop'

    - True Action
       Action : Alert
       Text : 'Uploaded'

From the output, When I drag & drop file to the region, I am not getting any alert message.

### APEX version (4.2.6 / 5.0.3)
Apex 5.0.3

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
Tomcat 7, ORDS 3.0.6,  Linux Redhat x64

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by Dani3lSun** [comment]
Hi @nikhilbutani 
I tested this on my APEX 5.0.4 and 5.1.2 instances. On both this event worked as expected...
Maybe an error occurred and the error event was triggered? Or you had the wrong region in the event selection type settings?
If you would like to do something when uploading (of all files) finished then please use the **Dropzone Upload completed** event. The one you used is triggered for every single file...
