### ISSUE TITLE
Allow to use substitution strings in the collection name

### ISSUE THREAD

**Issue by vincentmorneau** [Dani3lSun/apex-plugin-dropzone#31]
### Expected behavior
Allow to use substitution strings in the collection name.

![image](https://user-images.githubusercontent.com/5391291/30933558-e58727b4-a398-11e7-8240-b5e4448c77f9.png)

### Actual behavior
Has empty string instead.

### APEX version (4.2.6 / 5.0.3)
5.1.1

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome

---

Or we could also allow to store values in c003, c004, c005 etc to customize the collection further.

**Comment by martindsouza** [comment]
I talked to @vincentmorneau  about this and using [`apex_plugin_util.replace_substitutions`](apex_plugin_util.replace_substitutions) may be an option to parse the collection/table name.

**Comment by Dani3lSun** [comment]
I also thought about using **apex_plugin_util.replace_substitutions** for it, thanks for clarifying this. I will address these changes in the upcoming release!

**Comment by vincentmorneau** [comment]
There may be more to it, but doing this fixed it for me:

![image](https://user-images.githubusercontent.com/5391291/31032997-7a226868-a52c-11e7-8d90-3e40b3d11397.png)

Looking forward to the next release!
