### ISSUE TITLE
Execution of the statement was unsuccessful. ORA-20001: Error creating plug-in id="129251394625485599" ORA-20001: ERR-1014 Application not found. 

### ISSUE THREAD

**Issue by maahjoor** [Dani3lSun/apex-plugin-dropzone#32]
### Expected behavior

i was trying to install region_type_plugin_de_danielh_dropzone2.sql under the source directory into my apex page. it should install the application
### Actual behavior
it throw the error 
ORA-20001: Error creating plug-in id="129251394625485599" ORA-20001: ERR-1014 Application not found. 
### Steps to reproduce the issue

install it in apex 5.1.1
### APEX version (4.2.6 / 5.0.3)
 apex 5.1.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

ORDS 3
### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Firefox 55.0.3

**Comment by Dani3lSun** [comment]
Hi @maahjoor 
seems that you try to import the plugin somehow wrong...Maybe you try to import it as application...
To import this plugin, and all other plugins correctly do this steps:

1) Go to your Application --> Shared Components --> Plug-ins
2) Click to import button
3) Go through the import wizard and upload the plugin SQL file

<img width="1679" alt="shared_components" src="https://user-images.githubusercontent.com/698942/31437119-761646fc-ae84-11e7-8060-12a436907d15.png">
<img width="1679" alt="plug-ins" src="https://user-images.githubusercontent.com/698942/31437125-7b27b004-ae84-11e7-9604-6e11fe98faec.png">

**Comment by maahjoor** [comment]
Hi,

Thank you very much for the clarification. I have downloaded your demo app.
Great work.

Thanks a lot.

Regards
Muhammad Idrees
Oracle DBA/Developer & System Analyst
Higher College of Technology,
Muscat, Oman


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
