### ISSUE TITLE
Data type BLOB can not be converted to VARCHAR2!

### ISSUE THREAD

**Issue by maahjoor** [Dani3lSun/apex-plugin-dropzone#34]
![image](https://user-images.githubusercontent.com/16849793/31858651-06b12f6a-b70e-11e7-9d9d-e38b4cc458ae.png)
### Expected behavior
the form should be opening

### Actual behavior

the form is not opening and throwing the error Data type BLOB can not be converted to VARCHAR2!. i have uploaded the image with this thread
### Steps to reproduce the issue

insert one record to the custom table and try to re-access the form
### APEX version (4.2.6 / 5.0.3)
5.1.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Firefox 56.0.1

**Comment by maahjoor** [comment]
hi,

the issue was because of another interactive grid which was selecting rows from the files table. when i delete that grid, the form is working fine. 

Thank you.

**Comment by Dani3lSun** [comment]
Not an plugin issue...
