### ISSUE TITLE
No Data Found when looking for uploaded files in collection - using default method - on 2 environments

### ISSUE THREAD

**Issue by etaygudai** [Dani3lSun/apex-plugin-dropzone#38]
Hello Dani3lSun,

1. Thanks for all plugins you are sharing with us !!! awesome.

2. I tried to implement DropZone 2 on both of my apex environments ( 1 with Apache + Tomecat and the second is tomcat alone ).

3. Did the following only : 
Import plugin file "region_type_plugin_de_danielh_dropzone2.sql" from source directory into your application
Added the Dropzone2 plugin region.

4. Upload on website looks good (see attached printScreen link : [printScreen](https://www.dropbox.com/s/c4cng2kc2ralsgz/printScreenDanielSun.jpg?dl=0) ) , yet, I can't see the files stored in the collection table running ( getting NO-DATA-FOUND ): 

SELECT c001    AS filename,
       c002    AS mime_type,
       d001    AS date_created,
       n001    AS file_id,
       blob001 AS file_content
  FROM apex_collections
 WHERE collection_name = 'DROPZONE_UPLOAD';

Please advise what I am missing ? 

Regards
Etay G

**Comment by Dani3lSun** [comment]
Hi @etaygudai 

if you open your browser console, do you see any error messages?
You can turn on APEX debug mode and then upload some files, after that you open the debug messsages and can see if everything is fine or if some ORA error messages occur...

For you environment I would suggest you to use "Chunked" upload method because Tomcat has a 2MB max file size limitation, and chunked upload only uploads 1 MB chunks per default...

And btw: You can´t select a blob column in your report, maybe this is the error...And APEX collections only have values in the same APEX session, this means if you select it via SQL Workshop or any SQL Developer you can´t see the files...

**Comment by etaygudai** [comment]
Hello Dani3lSun,

Thanks.

see movie : https://www.dropbox.com/s/5ua4wz0xfuoz1fv/OracleApexOpenBuilder2.wmv?dl=0

1. In console : no error.
2. In Debug ( if I am not missing something ) : no error.
3. still no data found in apex_collections. ( even if BLOB is not possible to display, Apex SQL usually shows other columns ( same goes for CLOB if I recall correctly) 
4. Tried also chunked method, with no change ( small file size of course ).

Any other ideas ? ( before launching ORDS in standalone mode )

Regards
Etay G

**Comment by Dani3lSun** [comment]
Hi @etaygudai 
seems fine as far as I can see in this screen cast...
Can you please try to install the demo app and test if this works? You will find it here:
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v.2.2.1

Thanks!

**Comment by etaygudai** [comment]
Hello Dani3lSun,

Thank you for this demo app. ( missed that - very helpful for the kick start - I may suggest to include it in the plugin zip as well).

You were right ! ( my apology for wasting your time ),  as I didn't play around too much  with the apex_collections, I didn't notice that SQL results can be gained only from within the apex app page during session itself ( and not from Apex SQL Commands apex page )  as files can be saved to blob **permanently** only through transferring from apex_collections to custom table ) . in other words was too lazy to add the mentioned above SQL within page region :-)

Results are now as expected everything works correctly also using chunk method inserted to my custom table.

Thank you and keep us enjoying from your work :-).

Appreciated.
Etay G

**Comment by Dani3lSun** [comment]
Great that it works! Have fun and if you have questions, don´t mind to open up a issue here on GitHub...
