### ISSUE TITLE
Insert files in custom table

### ISSUE THREAD

**Issue by dpccrt87** [Dani3lSun/apex-plugin-dropzone#41]
I want to upload multiples PDF files in my own and custom table using DropZone APEX Plugin.
So for that, i created another version, following your article [https://github.com/Dani3lSun/apex-plugin-dropzone#inserting-uploaded-files-into-your-own-tables](url)  and using my own table '**TSL_CC_PIECES**'

But the issue still here, i cant store the files in my custom table.

The demonstration of issue, on apex.oracle.com with this credentials:
Workspace: ws_formation
Username: asoukaina
Password: s@boulah123

I used the Application 200218 - Dropzone Demo.

Thank you a lot for help.

NB:
APEX version (5.1)
Used web server / version and platform (ORDS 3.0.3 / Tomcat 9 / win7 x64)
web browser / version and platform (Chrome ,Firefox )

**Comment by Dani3lSun** [comment]
Hi @dpccrt87 
I just checked you code and saw that you use "Custom Table", but if all files are inserted you loop over the collection. Thus you´re using cxustom table the collection is empty and does not exist.

I changed the plugin setting to use the APEX Collection, now the insert is executed. But it seems that a required column is not set. I don´t know your data model but just set all required columns in the "Store Data" Dynmaic Action PL/SQL Code and you should be fine...
<img width="620" alt="screen shot 2018-02-20 at 16 18 50" src="https://user-images.githubusercontent.com/698942/36432281-1b63f0b8-165a-11e8-9a7f-dc5d789f4370.png">

**Comment by dpccrt87** [comment]
Where did you did theses modifications ?

**Comment by Dani3lSun** [comment]
Yeah I know what you want to do, but you can´t choose as storage type "custom table" and then select the files of an APEX collection in the PL/SQL code. Thus you choose "custom table" the collection does not exist. So I changed this:
<img width="287" alt="page_designer" src="https://user-images.githubusercontent.com/698942/36447580-102b4388-1685-11e8-90a5-2771cdbc8b19.png">
![36436603-a6c9982c-165c-11e8-9333-21d7d2834efa](https://user-images.githubusercontent.com/698942/36447736-88291de2-1685-11e8-852e-a00750466314.png)

**Comment by dpccrt87** [comment]
You can see my application now, its works using both custom table and apex collection
