### ISSUE TITLE
How to accept accented messages

### ISSUE THREAD

**Issue by dpccrt87** [Dani3lSun/apex-plugin-dropzone#44]
Hi Mr Dani3lsun,
Im sorry for disturbing you again.

Actually, i want to translate the messages to french langage, but when i did it i get this result:
![custom message_dz](https://user-images.githubusercontent.com/12938748/36603643-5ce6cf82-18b3-11e8-8269-1f654c6d030f.PNG)

How can i fix it ?
Thank you for help.

APEX version (5.1)
Used web server & version and platform (Apache 9 / win x64)
Used web browser (Chrome )

**Comment by Dani3lSun** [comment]
This was fixed in the latest release:
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v.2.2.3
So just install this version...
