### ISSUE TITLE
How to download and delete uploaded files from custom table

### ISSUE THREAD

**Issue by dpccrt87** [Dani3lSun/apex-plugin-dropzone#45]
Hi Mr Dani3lSun,
I hope, this post it will be my last in this plugin ;) 

As you know im using dropzone plugin with my custom table.
Now i want to download and delete the uploded files.
For that i created IR as:
```
SELECT 
ID_PIECE,	
UTI_CODE_USER,
DOS_NUMERO_DOSSIER,
FILE_CONTENT,
MIMETYPE,
FILENAME,
UPLOAD_DATE,
FK_ID,
''    AS download,
''    AS delete

FROM    <table_name>
WHERE    DOS_NUMERO_DOSSIER= :P11_DOS_ID
```
![tab](https://user-images.githubusercontent.com/12938748/36607734-6b856768-18bf-11e8-9291-118c9d4fcaf1.PNG)

And in the download column, i did: URL LINK:
`f?p=&APP_ID.:11:&APP_SESSION.:APPLICATION_PROCESS=DOWNLOAD_TSL_FILE::::&X01=#ID_PIECE#`

![download](https://user-images.githubusercontent.com/12938748/36607466-a261c728-18be-11e8-86c5-217076b4471f.png)
 
And in AJAX CALLBACK Process:
![download_2](https://user-images.githubusercontent.com/12938748/36607505-b8b0a3fa-18be-11e8-9ce0-50ca2fe0fe9c.png)
But when i run page, i get blank page
![res_dz](https://user-images.githubusercontent.com/12938748/36607621-0bcd62a8-18bf-11e8-8280-cdc4cc169387.png)

So how can i fix this issue, and how can i do delete file too ?

Thank you for help.

APEX version (5.1)
Used web server & version and platform (Apache 9 / win x64)
Used web browser (Chrome )

**Comment by Dani3lSun** [comment]
Hi @dpccrt87 

Please ask such basic things, which have nothing really to do with this plugins, either on apex.world Slack channel or the Oracle APEX forum.

But as far as I can see you always mix up APEX Collection and your custom table. So please try to understand what the code from the demo app does.
1) The files are stored in YOUR table
2) You do an select on APEX collection in the PL/SQL code of the download procedure
--> You have to do an select on your table not from the collection (After uploading and inserting into your own table, the collection was deleted)

Here is a nice article about downloading files (Google translated):
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fapex.oracle.com%2Fpls%2Fapex%2Fgermancommunities%2Fapexcommunity%2Ftipp%2F4221%2Findex.html&edit-text=&act=url

And for delete: You Have to write the PK of your table into an hidden item and do an delete via Dynamic Action (Execute PL/SQL code)
