### ISSUE TITLE
Apex 18.1 Not functioning as is. Will there be a version for 18.1

### ISSUE THREAD

**Issue by bampotusa** [Dani3lSun/apex-plugin-dropzone#49]
### Expected behavior
On Click should open file browser for file selections

### Actual behavior
Drag and Drop and Click functionality is disabled. No action on click

### Steps to reproduce the issue
Install dropzone on Apex 18.1

### APEX version (4.2.6 / 5.0.3)
18.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Redhat Linux x64

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome

**Comment by Dani3lSun** [comment]
Hi @bampotusa 

my plugin demo app is running fine on apex.oracle.com which is on APEX version 18.1, my local development env is also running APEX 18.1, and I have no problems...

Are you using the newest Dropzone version? Thus I made some 5.2/18.1 adjustments there...You can see it in the changelog:
https://github.com/Dani3lSun/apex-plugin-dropzone#changelog

To be safe you should at least use some 2.2.x version, at best go with the newest one!

**Comment by bampotusa** [comment]
Thanks I will get that version. 

P.S I will also send you a beer. This is the best plug in I have ever used.

**Comment by bampotusa** [comment]
Yep that did it. The latest version works great

**Comment by Dani3lSun** [comment]
Great that it works! ;)

**Comment by Dani3lSun** [comment]
Btw thanks for the beer! 👍
