### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by Fatehcis** [Dani3lSun/apex-plugin-dropzone#5]
Hello, 
Your contributions are highly appreciated. 

Are you planning to support external storage e..g, the files are uploaded to Amazon or Oracle Cloud Storage, then the files link are stored in the DB.

**Comment by Dani3lSun** [comment]
Hi @Fatehcis

you can do this already now. The files are uploaded to a temp apex_collection, from there you can pick the files and upload it to your favorite cloud location, either via web service or a locally mounted cloud storage on your database server...
I do similar thing with the open xchange webdav rest api at work, a code sample for example could look like this:
New Dynamic Action:
- Event: Dropzone upload completed
- Action: Execute PL/SQL code
- Code
```
DECLARE
  --
  CURSOR l_cur_dz_files IS
    SELECT n001    AS file_id,
           c001    AS filename,
           c002    AS mime_type,
           d001    AS date_created,
           blob001 AS file_content
      FROM apex_collections
     WHERE collection_name = 'DROPZONE_UPLOAD';
BEGIN
  --
  -- loop over dropzone files and upload with plsql procedure to other location
  FOR l_rec_dz_files IN l_cur_dz_files LOOP
    your_api.your_upload_prc(i_filename     => l_rec_dz_files.filename,
                             i_mimetype     => l_rec_dz_files.mime_type,
                             i_file_content => l_rec_dz_files.file_content);
  END LOOP;
  -- delete collection after upload
  apex_collection.delete_collection(p_collection_name => 'DROPZONE_UPLOAD');
END;
```
Hope this helps!

**Comment by Fatehcis** [comment]
Ok, thanks for the thorough answer

Assalamu Alaikum, السلام عليكم و رحمة الله و بركاته,





  Fateh Almsaddi, *COO*, M: (+971) 55 667 5271 <+971556675271>
------------------------------
[image: FAM Properties] <http://dubai.famproperties.com/>
Building 13, Office 303 & 304
Bay Square - Business Bay
Burj Khalifa District
P.O Box 215088
Dubai, UAE
*fäm*Properties.com <http://dubai.famproperties.com/>
Location Map
<https://www.google.com/maps/place/f%C3%A4m+Properties+-+Dubai+Real+Estate+Brokers/@25.1870084,55.2816753,17z/data=!4m2!3m1!1s0x0000000000000000:0x64b7bc4ca8ecb767?hl=en-US>

*Stay Connected*
[image: Facebook] <https://www.facebook.com/famproperties>   [image:
LinkedIn] <http://www.linkedin.com/in/famproperties>   [image: Twitter]
<https://twitter.com/famproperties12>   [image: Youtube]
<http://www.youtube.com/user/famproperties123>   [image: Blog]
<http://blog.famproperties.com/>   [image: Plus]
<https://plus.google.com/+Famproperties2>

 Please consider the environment before printing this email.
