### ISSUE TITLE
How to limit to select only one file?

### ISSUE THREAD

**Issue by rafael-trevisan** [Dani3lSun/apex-plugin-dropzone#50]
Hey Dani3lSun,

Great plugin again!

I was wondering how I could limit the user to select only one file.

Although setting "Max. File" to 1 the user still can select as many files they want.

I'm thing to execute `$('.dz-hidden-input').prop('disabled', true);` when a DA "max Files Exceeded" happens but I am not sure if that is the best approach.

**Comment by Dani3lSun** [comment]
If you click the dropzone it should only be possible to select 1 file if your configured it for just 1 file...
When drag&drop is in the game a user can drop as many files as they like, thus there is no file dialog which can limit this...
But the plugin normally handles it, thus only the first file is really uploaded to the server, the other files should get an error that max files has exceeded...
Btw sorry for the late response! ;) I was on holidays

**Comment by rafael-trevisan** [comment]
It's all right.

I got what I needed through a DA "Dropzone File Added":

```
const dz = Dropzone.forElement('.dropzone');

  const files = dz.getFilesWithStatus('success');
  if (files.length > 0) {    
    for (let i = 0; i < files.length; i += 1) {
      dz.removeFile(files[i]);
    }
  }
```

Of course, I'm truncating also the collection and it's perfect 😉
