### ISSUE TITLE
Normal upload mechanism for large files

### ISSUE THREAD

**Issue by MirelaGeorgescu** [Dani3lSun/apex-plugin-dropzone#51]
### Expected behavior
Should be uploaded

### Actual behavior
Are not uploaded, with error message "error"

### Steps to reproduce the issue
Configure the plugin to Upload Mechanism = "Normal" and max. Filesize in MB = "10"

### APEX version (4.2.6 / 5.0.3)
5.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS (on Glassfish 4.1) + IIS server (7.5)

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome

Hi Danny, 
Great plugin! 
We do have an issue when uploading larger files in "Normal upload mechanism" mode.
 I've seen that there were issues in different application server configurations. In our case in Glassfish is the Max Post Size -1 (changing it to something large did not help). We could not find such a setting in IIS.
Do you have any ideas (except to change the mechanism to "chunked")? 

Here are the Options, if relevant:
acceptedFiles:"application/pdf"
ajaxIdentifier:"6K3iUTSZXRrXxBKFm9kFmlWNmQ4Tu74TnM6ESXvSroQ"
cancelUploadConfirmMessage:"Are you sure you want to cancel this upload?"
cancelUploadMessage:"Cancel upload"
chunkSize:"1048576"
clickable:"true"
deleteFiles:"false"
displayMessage:"Drop PDF file(s) here or click to upload."
fallbackMessage:"Your browser does not support drag&#x27;n&#x27;drop file uploads."
fileTooBigMessage:"File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB."
invalidFileTypeMessage:"You can not upload files of this type."
maxFiles:256
maxFilesMessage:"You can not upload more than {{maxFiles}} files."
maxFilesize:10
pluginPrefix:"/app_files/hubdev/scn/plugins/dropzone/"
removeAfterUpload:"true"
removeFileMessage:"Remove file"
resizeImages:"false"
showFilePreview:"false"
supportCopyPaste:"false"
uploadMechanism:"NORMAL"

And the debug of the error:
apexDropzone.uploadDzFiles Error error
apexDropzone.handlePluginEvents - error event
apexDropzone.handlePluginEvents - complete event
apexDropzone.handlePluginEvents - totaluploadprogress event
apexDropzone.handlePluginEvents - removedfile event

Regards,
Mirela

**Comment by Dani3lSun** [comment]
If you just get the "error" message it indeed points into the maxPostSize issue, does the DB request doesn´t finish you won´t get a proper error message...
Normally I suggest to use chunked upload, I only use this mechanism these days...
Somewhere in you webserver config should be some hard limit on post requests...
