### ISSUE TITLE
Dynamic Action not executing

### ISSUE THREAD

**Issue by sgutschi** [Dani3lSun/apex-plugin-dropzone#52]
### Expected behavior
It should execute my dynamic action, which should show an alert-msg.

### Actual behavior
The dynamic action (Dropzone Upload Complete) is not triggered. However, the events for the dropzone are executed and the files are saved into the APEX_COLLECTION.

![capture](https://user-images.githubusercontent.com/12330046/42500628-18894d48-8432-11e8-9676-a0074a34e903.PNG)

### APEX version (4.2.6 / 5.0.3)
5.1

**Comment by Dani3lSun** [comment]
Hi @sgutschi 
could it be that your event selection type is not correct? The DA event should bind to the dropzone region, see this screenshot:
<img width="1679" alt="page_designer" src="https://user-images.githubusercontent.com/698942/42508554-3730d9c0-8449-11e8-9097-926c2e2ea68f.png">
You could also try the demo app which is available here:
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v.2.2.4
This also uses the plugin events...

**Comment by sgutschi** [comment]
Hi,
unfortunately I have the same configuration as you have :
![capture2](https://user-images.githubusercontent.com/12330046/42509460-33d0a30c-844c-11e8-981a-cccd3f004c2d.PNG)

Do you have any other idea? :(

**Comment by Dani3lSun** [comment]
Hmm any JavaScript errors on the page? This would stop all further processing...
Does the demo app work in your workspace?

**Comment by sgutschi** [comment]
There are no errors in the console :(
Yeah, I imported the demo app into my workspace, this one works.

Strange...

**Comment by sgutschi** [comment]
After revisiting my problem, I finally found what's causing my problem! 

Previously I did not select a template for the Dropzone-Region, I just left it on '-Select-', since I had a wrapper-region around it anyway. 

However, after changing the template, all the Dynamic Actions are finally working!

Maybe include a note in the ReadMe section for this bug or, if you know how to prevent this, by updating the plug-in.

Anyway, thanks for this great (now finally completely working) plug-in! :)

**Comment by Dani3lSun** [comment]
Hey @sgutschi 
thanks for letting me know & great that it works now for you! :)
OK after reading this it is totally understandable, the DA trigger binds to the region, if you don´t choose an template the region-id is missing in the html of the page, e.g.
<div id="my-region">
  <div id="dropzone"></div>
</div>
So nothing to react on if this div-structure is missing...
