### ISSUE TITLE
I have added a filename A.pdf several times using the Dropzone plugin in my APEX. But suddenly I am not able to upload the same file with this name. If I change the name of the file, I can still upload it. Is there any place or registry or cache, where there is a limit on the same filename entries ? I am guessing that the file with same name is there in the registry or cache and now it is not allowing me to add more files with same name. Please suggest

### ISSUE THREAD

**Issue by abha3011** [Dani3lSun/apex-plugin-dropzone#54]
### Expected behavior
I should be able to upload the file with same name under different sessions.
### Actual behavior
I am not able to save the file with name A.pdf, but if i change the filename it gets uploaded successfully.

### Steps to reproduce the issue
1. Login to APEx
2. Click on dropzone box
3. Select file A.PDF and drag it in the dropzone
4. No records is found in the interactive grid below, where I am writing the query : 
  select C001 from apex_collections where  collection_name = 'DROPZONE_UPLOAD'
5. I change the name of the file to Abc.pdf and then drag it in the dropzone
6. It gets successfully uploade and can be seen in the interactive grid below.

### APEX version (4.2.6 / 5.0.3)
APEX version 18.1.0.00.45

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome and Firfox

**Comment by Dani3lSun** [comment]
Hi @abha3011 

this sounds strange...I tested it on my local env and it works if I do the steps you described above...
![dropzone](https://user-images.githubusercontent.com/698942/43522509-dd118126-9599-11e8-8516-68b21811a678.gif)
Do I do the same as you?

**Comment by abha3011** [comment]
hi,
Thanks for your reply. 
Yes, you are doing the same steps, but the diffrence is you have added the files only 3 -4 times.
Whereas, I have added this filename may be a hundred times during testing, over a period of time. Everytime it was getting added properly. But suddenly after numerous uploads,  i was not able to upload the file with same name. Then I tried changing the name and it got uploaded.

I am not sure why this is happening. Recently I read similar problem in microsoft outlook attachments, and there they had multiple files with same names in the registry, which was creating problem, and so they deleted those files from the temp folder in registry and then everything was fine.

so I am just wondering if this may be the case here as well ?

**Comment by abha3011** [comment]
![dropzone_error](https://user-images.githubusercontent.com/41986983/43524957-d6db18ba-95a0-11e8-9157-6109fcd9fa6c.gif)

I am attaching the steps for your reference.

**Comment by Dani3lSun** [comment]
I also tried it more times than the GIF shows, and neither had that issue...Can you try the following:
1) Visit your dropzone page
2) Open browser dev tools and open network tab
3) Upload a file & have a look at the response output of the failed upload
<img width="1680" alt="screen shot 2018-08-01 at 20 26 29" src="https://user-images.githubusercontent.com/698942/43540887-379629d8-95c9-11e8-8ebd-6a1368462ff1.png">

**Comment by abha3011** [comment]
Hello @Dani3lSun,

Thanks for your time . I tried to see the response for A.pdf file, but it shows "Success", Although the file is still not visible. I also tried with some other filename, for that also status is also "Success" but the file is visible in the interactive grid.
![media1](https://user-images.githubusercontent.com/41986983/43566252-1ead30e6-962e-11e8-9bca-8cb83c5a35e3.gif)

This looks very weird, and I am not able to resolve it. 
Please suggest.

Regards,
Abha

**Comment by abha3011** [comment]
Hello, 

I just noticed one more thing, in the wwv_flow_ajax. There are no values coming in under "Values" tag for A.pdf and total_rows = 0.

While if I change the name to ABCD.pdf, there are values under "Values" tag and total_rows = 1.

![media2](https://user-images.githubusercontent.com/41986983/43568217-4defe76c-9634-11e8-8912-55ba52c3090c.gif)

Your pointer really helped. Hope we are somewhere near to troubleshoot this error.

Regards,
Abha

**Comment by abha3011** [comment]
Hello Dani3lSun,

I am not able to resolve this issue,yet . Did you get any chance to look into it further ?

Regards,
Abha

**Comment by aldocano29** [comment]
I am facing kind of the same issue here... I have uploaded a file several times and now whenever I try to upload it again the plug in send this error inside the Network Tab:


{ "status": "error", "message": "File my filename NOT saved to APEX Collection COLLECTION_NAME", "code": "ORA-00600: internal error code, arguments: [25027], [11], [0], [], [], [], [], [], [], [], [], []", "id": "" }
