### ISSUE TITLE
Error during Rendering of region "DROPZONE_UPLOAD"

### ISSUE THREAD

**Issue by abha3011** [Dani3lSun/apex-plugin-dropzone#58]
Hi,

I have recently installed my working application from development environment to test environment. In my DEV environment the application with this plugin was working fine without any issues. But now I have exported and imported the same application in other environment. And when I try to run the application it gives me this error :  "Error during rendering of region DROPZONE_UPLOAD " . Can you please help.
Do I need to do any specific thing for the plugin import on different environment ?

### APEX version (4.2.6 / 5.0.3)
APEX version 18.1.0.00.45 on both the environements.

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Internet Explorer 11

**Comment by abha3011** [comment]
Hello ,
Can you please help regarding this. I am really not able to find, if I am missing something. 
I also tried to create a basic application again on Dev environment with no customization. Just added the plugin and created the report region to show the attachments. It works fine in Dev but when I exported the appilcation and imported it in TEst, I gets a blank page . I do not even get the upload dropbox . Can you please suggest is their any supporting files tht I need to install specifically on other environments. Right now, I just import the "region_type_plugin_de_danielh_dropzone2.sql" file from source folder in apex.

I am really stuck with this. Please suggest.

**Comment by Dani3lSun** [comment]
Hi @abha3011 
this seems really strange...
Which version of the plugin do you use?
Have you changed something in the plugin code itself? Thus when you outsource the integrated PL/SQL code for example to an package and forget to compile the package in prod the region would not work...
If you just use the original plugin, as is, there shouldn't be issues like that...Can you run that problematic page from prod in debug mode and copy paste the relating errors here?

**Comment by abha3011** [comment]
Hi,
No I haven't changed anything in the plugin. I just imported the sql file from your plugin definition.
When I ran my page in Debug mode in test environment I am getting errors where there is no data in the apexdropzone.js , dropzone.js files. Please see the screenshot. This same application works fine on my development environment though.

![error](https://user-images.githubusercontent.com/41986983/50584108-a68d1a00-0e6d-11e9-84a1-69c908abd06f.PNG)


So, that's why I am concerned, do I need to take any specific step when I move the exported application with plugin to other environment ?
Please suggest.
