### ISSUE TITLE
Antivirus Check?

### ISSUE THREAD

**Issue by JacoFourie1** [Dani3lSun/apex-plugin-dropzone#60]
Hi Daniel. We made some progress around the Virus scanning issue. We now have Sophos UTM infront as a reverse proxy server that will do virus scans as files are being uploaded. 

What will happen is that if there is a virus the UTM will send back a HTML response of "400 - Bad Request".
I can see the html is coming to the browser. I also can see that the File -Error DA is firing as you can see my error message is "File Upload Error". So my question to you is how do I get to that response text to show it in the error message ? Do you have some Javascript code I could use to catch the response in the File-Error DA ? I assume the response is on the AJAX call to upload the file to ORDS. So it should be possible to get to it. I just don't know how.

![image](https://user-images.githubusercontent.com/26320171/52401773-2b9dcb80-2acb-11e9-93d7-407df8c83314.png)

**Comment by JacoFourie1** [comment]
Hi. 

I assume it is this code that is catching the error.

```
if (vJsonReturn.status == 'error') {
                // APEX event
                apex.debug.log('apexDropzone.uploadDzFiles Error', vJsonReturn.message, vJsonReturn.code);
                apex.event.trigger('#' + pRegionId, 'dropzone-upload-error', vJsonReturn);
                // file status
                file.status = Dropzone.ERROR;
                pDropzone.emit("error", file, "Database error during file upload");
```
Is there a way to pass the response HTML also ?

**Comment by Dani3lSun** [comment]
Hey @JacoFourie1 ,

you could try to use the integrated plugin events for this.

Create a new DA, with Event "Dropzone File Upload Error (AJAX)" and for testing just log "this.data" to console or something:

<img width="1679" alt="cropper_and_page_designer" src="https://user-images.githubusercontent.com/698942/52414111-ae328500-2ae3-11e9-977f-700b6b31d321.png">
<img width="1679" alt="cropper_and_page_designer" src="https://user-images.githubusercontent.com/698942/52414142-c73b3600-2ae3-11e9-9a65-0413b8ae9ddd.png">

**Comment by JacoFourie1** [comment]
Hi Daniel. The event does fire yes. But "this.data" does not have the response from the UTM in it.

![image](https://user-images.githubusercontent.com/26320171/52414742-cd361480-2aed-11e9-9d9e-5361a1d5449d.png)

This is the HTML the UTM sends back when the AJEX call is made to upload the file.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
<h2>Error Reason</h2>The request was blocked because an uploaded file contains a virus (EICAR-AV-Test).</p>
</body></html>
```

**Comment by JacoFourie1** [comment]
OK I see it in the xhr object. Now how do I get to it ?

![image](https://user-images.githubusercontent.com/26320171/52415542-e9d34c00-2aef-11e9-9149-185d50120705.png)

**Comment by JacoFourie1** [comment]
HEEEEEEEHAAAAAAA !!!! I got it working. Thanks a lot.

**Comment by Dani3lSun** [comment]
Ah saw it to late, that's great!
Nevertheless you could do it with some javascript:
```
var errorObject = this.data.
// check http status for virus error
if(errorObject.xhr.status === 400 || errorObject.xhr.statusText === 'Bad Request') {
  // get clean error message from server response
  var serverResponseText = errorObject.xhr.responseText;
  var result = serverResponseText.match(/<\/h2>(.*)<\/p>/g).map(function(val) {
    var errorMessage = val.replace('</h2>', '').replace('</p>', '');
    // show apex error message
    apex.message.clearErrors();
    apex.message.showErrors([{
      type: "error",
      location: "page",
      message: errorMessage,
      unsafe: false
    }]);
  });
}
```

**Comment by JacoFourie1** [comment]
Thanks so much. One more question, How do you remove a file from the upload region ?

**Comment by Dani3lSun** [comment]
You could use a function like this:
https://github.com/Dani3lSun/apex-plugin-dropzone/issues/36#issuecomment-338494741
If you don't have the file-id you have to change the function to use the filename for example...

**Comment by JacoFourie1** [comment]
Is there a way the set the error text below the file icon ? If there is a virus it just says error.

**Comment by Dani3lSun** [comment]
I think the best is to have a look at the official dropzone library:
https://www.dropzonejs.com/
You will also find a lot of howtos if you google "dropzone xxx"
