### ISSUE TITLE
How to show each image on report?

### ISSUE THREAD

**Issue by rvnobre** [Dani3lSun/apex-plugin-dropzone#61]
### Expected behavior
Using drop zone plugin in your example you have a column Download. How to setup imagw preview?  Thanks

**Comment by Dani3lSun** [comment]
Hi @rvnobre 
I think this issue has nothing to do with the plugin itself, thus as far as I understand you want to show the stored BLOBs in an Report or Interactive Report...Just google it how to display stored image BLOBs in APEX, there are several hits and of course multiple solutions to this problem...

https://stackoverflow.com/questions/46118518/oracle-apex-show-picture-in-report-from-a-different-table
http://www.apexninjas.com/blog/2011/09/uploading-and-displaying-images-in-apex/
