### ISSUE TITLE
Receiving Javascript Error (Developer Console Only) Apex 19.1

### ISSUE THREAD

**Issue by bampotusa** [Dani3lSun/apex-plugin-dropzone#64]
### Expected behavior
Upload a small SQL file. File Uploads No issues Apex 19.1)

### Actual behavior
File does upload, but developer console show sql.png not found. I expect that is the image its looking at for the file type. Maybe there is a way to add more pngs as needed ?

### Steps to reproduce the issue
Create a small 1 line sql file named step1.sql save and upload. Have developer console running to see error (Apex 19 shows an alert on the developer toolbar also)

### APEX version (4.2.6 / 5.0.3)
19.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS 19/ Tomcat & Apache Linux

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome

**Comment by Dani3lSun** [comment]
Hi @bampotusa 
sorry for the late response!
Yeah you are right, the plugin searches for an file called -file-extension-.png, in your example it would be sql.png
You can upload your own files when you go to shared components --> plugins --> dropzone. Then upload you own file under plugins static files under the "img" folder

**Comment by bampotusa** [comment]
Many thanks, that worked.
