### ISSUE TITLE
How to make attaching a document mandatory

### ISSUE THREAD

**Issue by dpccrt87** [Dani3lSun/apex-plugin-dropzone#65]
Hi Daniel,
Im using Dropzone 2 plugin (version 2.2.1) with apex 18.2.0, and i want to know if is it possible to set the Dropzone2 plugin item to be required ?

Thank you for help.

NB:
APEX version (18.2.0)
Used web server / version and platform (ORDS 18.2.0 / Apache-Tomcat 9.0.10 / win x64)
Used web browser / version and platform (Chrome 48 Windows/ Windows Server 2016)

**Comment by Dani3lSun** [comment]
Hi @dpccrt87 
sorry for the late response...:(
Hmm you could always use an APEX validation to query the Dropzone Collection, if no results are in there then no file had beed uploaded...

**Comment by dpccrt87** [comment]
Hi Dani3lSun,
Thank you for reply, i will test it
