### ISSUE TITLE
Seems like ORDS is needed

### ISSUE THREAD

**Issue by GasparYYC** [Dani3lSun/apex-plugin-dropzone#67]
Hi.
 Just reporting that my app with the Plugin-dropzone (latest version) does not work on an APEX  Server with just Embedded PL/SQL Gateway.
I have moved it to a server with ORDS and works fine. (I tried twice the same file)
The error is the same as issue #66 
Based on the DA firing is the FileUploadError is what is tripped.

Note: Both environments are APEX v19.1 and the one with ORDS is: v18.3.0.r2701456

Cheers!

**Comment by Dani3lSun** [comment]
Hi @GasparYYC 
which upload method do you use? I don't have an env with embedded PL/SQL gateway, but it should at least work with the chunked method...

**Comment by GasparYYC** [comment]
Hi @Dani3lSun 
 Sorry for the very-very late reply.

I have just confirmed on Oracle EPG to get it to work I have to select  "Chunked Upload". When ORDS is available then "Normal Upload" works perfectly fine.

I recommend you edit the documentation specifying that for Oracle EPG the plug-in must select "Chunked upload".


Thank you.
-Gaspar
