### ISSUE TITLE
File Upload Error in  www_flow.ajax (403)

### ISSUE THREAD

**Issue by HAfsari** [Dani3lSun/apex-plugin-dropzone#70]
### Expected behavior
File Upload Error

### Actual behavior

![image](https://user-images.githubusercontent.com/14145343/64113252-97b78800-cdab-11e9-8ef7-49c874500f99.png)

### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/14145343/64113430-1f9d9200-cdac-11e9-869c-c4c03e65ca36.png)

### APEX version (4.2.6 / 5.0.3)

Application Express 18.1.0.00.45

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

Oracle web logic http server 
### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by Dani3lSun** [comment]
Hi @HAfsari 
yeah this is a "bug" or strange behavior in Oracle APEX...
APEX or ORDS validates each request to the DB, the default function used for this validations is "wwv_flow_epg_include_modules.authorize", normally you should see an entry like this in your ORDS defaults.xml file:
```
<entry key="security.requestValidationFunction">wwv_flow_epg_include_modules.authorize</entry>
```
I debugged this function some time ago, and APEX checks if an file upload occurs and only allows WWV_FLOW.ACCEPT (Submit) endpoint at this stage, but the dropzone plugin uses WWV_FLOW.SHOW or WWV_FLOW.AJAX (AJAX)...At the end validations fails and you get the 403 error...
I already talked with the dev team about that problem, and they fixed it in APEX 19.1!

The bigger problem is, that ORDS caches the validation result. So if the validations fails (403), every other AJAX call also fails...But the good thing is, you can use this caching for an workaround, so you don't have to wait for an APEX 19.1 installation...Just put a single on page load DA on the upload page which executes PL/SQL Code (AJAX call), with a dummy code like this:

```
BEGIN
  NULL;
END;
```
Now ORDS caches the positive validation result, and after that the dropzone region should work...
I hope this is helpful for you! :)
