### ISSUE TITLE
update additional files when upload complete

### ISSUE THREAD

**Issue by uvarol** [Dani3lSun/apex-plugin-dropzone#71]
### Expected behavior

When an upload is complete, I want to update a few more additional fields in the custom_upload_table associated with this process.
How can I do it?

### APEX version (4.2.6 / 5.0.3)

5.1.4

**Comment by Dani3lSun** [comment]
In this case, I would upload the files to an APEX collection and afterwards process the files from there to insert them into a custom table:
https://github.com/Dani3lSun/apex-plugin-dropzone#inserting-uploaded-files-into-your-own-tables
