### ISSUE TITLE
Onload default uploaded files

### ISSUE THREAD

**Issue by Ashwin2188** [Dani3lSun/apex-plugin-dropzone#74]
### Expected behavior
Show already uploaded files on page load

### Actual behavior
Display the documents that are uploaded

### Steps to reproduce the issue
Populated the collection on page load. Inside the dropzone region, can not see the populated files.

### APEX version (4.2.6 / 5.0.3)
19.2

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS 

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome

**Comment by Dani3lSun** [comment]
Hi @Ashwin2188 
I‘m not really planning to add any bigger new features to this plugin...
Nevertheless I like this idea and this is one of the features of the just released file uploader by FOEX:
https://www.foex.at/file-upload-image-editor/

It‘s commercial but supported by a very well known company & team...

**Comment by Ashwin2188** [comment]
Thanks for the update...we will try to show a table below the util with already uploaded files. I will see if I can do any changes to. the plugin,

Thanks alot for the plugin.
