### ISSUE TITLE
max. Filesize in MB - use parseFloat instead of parseInt

### ISSUE THREAD

**Issue by Gwen42** [Dani3lSun/apex-plugin-dropzone#8]
I wanted to set the maximum file size to 1.5 MB and realized the plugin made 1 MB out of it. 

Wouldn't it be better to change `parseInt` to `parseFloat` in apexdropzone.js? Or is there a reason you used `parseInt` for this parameter?

This is the line in `apexDropzoneFnc`:
`var vMaxFileSize = parseInt(vOptions.maxFilesize);`

**Comment by Dani3lSun** [comment]
Hi @Gwen42 
thanks for the hint, thought integer values would last for most people...
I will test it for the next release, and if it doesn´t make problems with the dropzone library I will change it!

**Comment by Dani3lSun** [comment]
new version 1.9.5 now supports float numbers as max file size!
Sorry that it takes so long ;)
