### ISSUE TITLE
Not Mobile Responsive. Please help

### ISSUE THREAD

**Issue by jateam22** [Dani3lSun/apex-plugin-dropzone#88]
### Expected behavior
Should be mobile responsive

### Actual behavior
In the mobile, the dropzone needs to be scrolled horizontally
![Snap1](https://user-images.githubusercontent.com/104968361/170670041-c3f83997-2031-460e-a9ba-94ec1a93272e.JPG)

### APEX version (4.2.6 / 5.0.3)
Apex version 22.1.0

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome in Android phone

**Comment by Dani3lSun** [comment]
Hi @jateam22 
just give the dropzone region a relative width like _100%_ then it should be responsive.
<img width="389" alt="Screen Shot 2022-06-02 at 08 42 28" src="https://user-images.githubusercontent.com/698942/171569446-17ff64b1-977c-4682-8b61-7aa86f0d9e17.png">
